// GENERATED by scripts/anime4k-transpile.mjs. Do not edit.
import type { Anime4KPass } from './types';

/** Lazy loaders: each shader becomes its own chunk, fetched only when used. */
export const ANIME4K_SHADERS = {
  Restore_CNN_L: () => import('./Restore_CNN_L').then((m) => m.default),
  Restore_CNN_M: () => import('./Restore_CNN_M').then((m) => m.default),
  Restore_CNN_S: () => import('./Restore_CNN_S').then((m) => m.default),
  Restore_CNN_VL: () => import('./Restore_CNN_VL').then((m) => m.default),
  Upscale_CNN_x2_L: () => import('./Upscale_CNN_x2_L').then((m) => m.default),
  Upscale_CNN_x2_M: () => import('./Upscale_CNN_x2_M').then((m) => m.default),
  Upscale_CNN_x2_S: () => import('./Upscale_CNN_x2_S').then((m) => m.default),
  Upscale_CNN_x2_VL: () => import('./Upscale_CNN_x2_VL').then((m) => m.default),
  Upscale_Denoise_CNN_x2_M: () => import('./Upscale_Denoise_CNN_x2_M').then((m) => m.default),
  Upscale_Denoise_CNN_x2_VL: () => import('./Upscale_Denoise_CNN_x2_VL').then((m) => m.default),
} satisfies Record<string, () => Promise<Anime4KPass[]>>;

export type Anime4KShaderName = keyof typeof ANIME4K_SHADERS;
